# Site settings
title:Video Essay Hall of Fame
email:VideoEssayHOF@gmail.com
description: >
A site dedicated to preserving and celebrating the most influential video essays ever made.# this means to ignore newlines until 

baseurl: "/home/" # the subpath of your site, e.g. /blog/
url: "VideoEssayHOF.com" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
