title: Video Essay Hall of Fame
email: VideoEssayHOF@gmail.com
description: >
  A site dedicated to preserving and celebrating the most influential video essays ever made.
baseurl: "/home/" # the subpath of your site, e.g. /blog/
url: "https://videoessayhof" # the base hostname & protocol for your site

twitter_username: N/A
github_username: Videoessayhof

# Build settings
markdown: kramdown
